name: Smart Contract Security Audit

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  audit-job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: |
          pip install slither-analyzer solc-select jinja2
          solc-select install 0.5.17
          solc-select use 0.5.17

      - name: Run Audit Tool
        run: |
          python main.py

      - name: Upload Report
        uses: actions/upload-artifact@v4
        with:
          name: audit-report
          path: audit_report.html
